# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Indrome 
tagline:             ''
description:         ''
url:                 http://indrome.com
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Tobias
  url:               https://twitter.com/indrome
  email:             tobias@indrome.com 

# Custom vars
version:             1.0.0
